# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://anshajk.github.io/amazon_food_reviews/"

git_url = "https://github.com/anshajk/amazon_food_reviews/tree/master/"

def custom_doc_links(name): return None
